{% set name = "pyasn1-modules" %}
{% set version = "0.0.9" %}
{% set sha256 = "be0e4157e4a53551279d6c6e366b080527f5fd068616835b4abf32c14f657f5f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pyasn1 >=0.1.8

test:
  imports:
    - pyasn1_modules

about:
  home: http://sourceforge.net/projects/pyasn1/
  license: BSD 2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A collection of ASN.1-based protocols modules.

extra:
  recipe-maintainers:
    - jakirkham
    - pmlandwehr
