travis:
  secure:
    BINSTAR_TOKEN: K5qM2+CvQYZ90TDEpkMXW4HlBYpm8Mpu7A00ecM+B7hSvreBbA9arBG6GF/3CzD0+6dvtsLqwweRF7S4LeSjrakFLJEtqq0cAefQPXYMFsr0umUddc701kINg8qOVcAP+MwgKh82dg7jVtQfmyJgu/w0nauIlpXk1Gta3rNeijlFqG9rKIP8Fo0v7qGj42BUABNi9NZJ4c3APwtg0Sq5i9TVvYuS5U9SkI6+7gp8yIcK1kWIkGoAw8q+4NGgXZZxT/gpliR8ecgjdOtRWQfbkXH6+HKWX0c/2Fu7NDOM1IFyNvSG6tGDSKtqzK6ukfjQUbm0TvYxDvpNs8XwFCl4RzgIa6bQau3gZ08fUI13r5RSUgNb1Y5fUi6O6Ax2bxvNZQgPKy7iaQ0upCh1IW1YfCqbCUljrC1NPogWQm70TYUS3+a5ifTViqIZf/CWuBLJNLuW6PKNNA0/hbYMQ6rIgx/v8Gepmuazug26qUQ4r2nR3g36upvobhULkHjMMTt8Nt97imqUSV2xJFxbIQO2HAAVUv/Ya4XYD631FBdE2QnMmFSYBl2ZZyG3ZOETpI/VOEfaNbl5ETOaqcmh6L8ZKgdf+m5IkVr806LkB49dHT6AcWzjMDuixT0yh37kuAF7DKgzAFHht6YT400gEQhL/p12z9AlcccCcodAooZ0ViQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
