travis:
  secure:
    BINSTAR_TOKEN: VgSdUIMbKN7TROriAb6dEchDt4J9capxruFLNdVx+1DWDdUkaJ6uV/1N7gk1eyAWhuh7YHLvGSGz7PmjkuVufvqR+Mzemo8luSbuvi5QtD+KWeg6rHkoSRC7b5i7M3DGU/OIcB8BHvRd3s9VW5yBOiDD0zh/pjOIKjDmW0z/eY/j1/RQsupFAOC1ZoWs+DiWMt6FAey5mJS6DmmBEY+V7Ip34oENx4DZ8vy6Std0m+p35uhh7r8Px38jEbxn+rADUcEe2D7NhpDDAk41NB14BMGsEeM2PC+zYZQdtBxLXRGFpHxlBKne8EayK7HiInGnMROrglB97y3/DlmqMygSribLsGgzS59nmz9w/hqAMydq8DlN1I+safBMm6lpwRf0x+zNhzXaHa59hZFDS4OBaiQ5oMMmS5ifSQ61FmKSObDUFJyCX7DhJ87rAcvP7h4mwnN43D5FThuqvRt1cbgKIYU0j5YkzBWkUzxYI2ULuO4Zrf3HYOn56ltuOBjMOrH3rs1NXo/8n5QujkWjhYLIIItUpusoT1/vA4fNPJ2kgKw3ABgKnCCOM/Yqne3+svEDTdfrSMwgjeW6tMvxzsTG+PizP1Q+lJqFShwIlX7sBcxAzi4qT4kcZP6l7FRl3t3RKJ086U6qK9zeorLkUWkE3dD0TFJft0vWERecX/gLWvk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
