travis:
  secure:
    BINSTAR_TOKEN: JPXI2EipXisg/nrnYVlOnO8GUKEK1VPjg4aiZmZcGftykIga/sny7ExzeF8FVWHzRMAdmhd2cMY/69eM7jZCVImvQovd6Lw1jqKHeGWqdIrFL64ZN2xzPiwFWyr5SjgI607vKYPqayAOyeMRG80cCDqymmjHXhrCRtqsLKodOy3/MmOKjtoJ3PpNjbMqAkgfz1gRUecr+qnee26U7g+7krVHhBFSlUryQdbztOtzynVCHc+UaSyRqEcYVRTTUv5Px1gtWvmCSanBgbbtAxXkn4oKKN8AqLJ6H3UdDJINUB79bP5Kq+nPbyUz9ysJ1S5g2D8ASCzHX4NbQpJ2s6Vgx3KBzKP3S0mZd0s81sUtxE0D+SVyve6RiTtZkTPfbTHLcOxz8D4IEp3rWGoh/vpmeXYsSbQ4FtsQSMpJRnHTBKJqbP9WYB7c5J8BOgympC39/vIzVnsKsoCCAkQwp0CeBr4FZ+X9ErhNLEJArJcKHdBq+ATSxX+Dl0AeZYP3CcNKvXqrNFnZPZbUUDyi8MykNEPsWA0xwIuT2+aQT0d5/oxJGQfdSjFAKI9PfVrLtA23gBIuvJDPgpyMCiP+NSJ82r+6kNgeVSJ7nO9gwMymJZ6Dw5vYuhITICGTFCWJqGkR9LX8kz5vStaoLxgm0qzfTC5luR2nJHo9OS0UBJI2h5M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
